availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-hub_username/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/docker-hub_password/versions/latest
      env: 'DOCKER_PASSWORD'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'echo $$DOCKER_PASSWORD | docker login --username=$$DOCKER_USERNAME --password-stdin']
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'build', '--platform', 'linux/amd64,linux/arm64', '-t', 'hlou/shopware-docker:latest-nginx', '--push', 'nginx']
timeout: '1800s'
images: ['hlou/shopware-docker']
options:
  logging: CLOUD_LOGGING_ONLY
