availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-hub_username/versions/latest
      env: 'DOCKER_USERNAME'
    - versionName: projects/$PROJECT_ID/secrets/docker-hub_password/versions/latest
      env: 'DOCKER_PASSWORD'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --platform=linux/amd64,linux/arm64 -t $$USERNAME/shopware-docker:latest-nginx nginx']
    secretEnv: ['DOCKER_USERNAME']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push $$USERNAME/shopware-docker:latest-nginx']
    secretEnv: ['DOCKER_USERNAME']
timeout: '1800s'
