name: Build
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  DOCKER_BUILDKIT: 1
  COSIGN_EXPERIMENTAL: 1
jobs:
  nginx:
    name: Build Nginx image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          tags: "hlou/shopware-docker:latest-nginx"
          context: nginx
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
